#!perl

# AUTHORITY
# DATE
# DIST
# VERSION

use strict;
use warnings;

use Getopt::Long qw(:config gnu_getopt no_ignore_case);

sub parse_cmdline {
    my $res = GetOptions(
        'help|h' => sub {
            print <<USAGE;
Usage:
  realpath [OPTIONS]... <FILE>...
  realpath --version (-v)
  realpath --help (-h, -?)

Options:

For more details, see the manpage/documentation.
USAGE
            exit 0;
        },
        'version|v' => sub {
            no warnings 'once';
            print "realpath (perl-based) version ".($main::VERSION // 'dev').
                "\n";
            exit 0;
        },
    );
    if ($res) {
        if (!@ARGV) {
            warn "realpath: Please specify one or more files\n";
            $res = 0;
        }
    }
    exit 99 if !$res;
}

sub run {
    require Cwd;
    for my $path (@ARGV) {
        print Cwd::realpath($path), "\n";
    }
}

# MAIN

parse_cmdline();
run();

1;
# ABSTRACT: Print the resolved (absolute) path
# PODNAME:

=head1 SYNOPSIS

 % realpath [OPTION]... <FILE>...
 % abspath  [OPTION]... <FILE>...

To demonstrate how C<realpath>, C<quickabspath>, and C<relpath> give you
different results:

 % pwd
 /home/ujang

 % mkdir dir1
 % ln -s dir1 sym1

 % cd sym1

 % realpath .
 /home/ujang/dir1

 % quickabspath .
 /home/ujang/sym1

 % relpath /home/ujang/dir1
 .
 % relpath /home/ujang/sym1
 ../sym1


=head1 DESCRIPTION

This is the Perl-based implementation alternative for the Unix utility
B<realpath> (also aliased to L<abspath>). It uses L<Cwd>'s C<realpath> (which is
the same as C<abs_path>) function. The function works by reading "." (the
current directory) and moving upwards until it reaches the root directory,
resolving symlinks along the way.


=head1 OPTIONS


=head1 EXIT CODES

0 on success.

99 on command-line options error.


=head1 FAQ


=head1 SEE ALSO

Unix utility B<realpath>

L<relpath>, L<quickabspath>

L<Cwd>

=cut
