#!perl

# DATE
# VERSION

use strict;
use warnings;

use Getopt::Long qw(:config gnu_getopt no_ignore_case);

sub parse_cmdline {
    my $res = GetOptions(
        'help|h' => sub {
            print <<USAGE;
Usage:
  realpath [OPTIONS]... <FILE>...
  realpath --version (-v)
  realpath --help (-h, -?)

Options:

For more details, see the manpage/documentation.
USAGE
            exit 0;
        },
        'version|v' => sub {
            no warnings 'once';
            print "realpath (perl-based) version ".($main::VERSION // 'dev').
                "\n";
            exit 0;
        },
    );
    if ($res) {
        if (!@ARGV) {
            warn "realpath: Please specify one or more files\n";
            $res = 0;
        }
    }
    exit 99 if !$res;
}

sub run {
    require Cwd;
    for my $path (@ARGV) {
        print Cwd::realpath($path), "\n";
    }
}

# MAIN

parse_cmdline();
run();

1;
# ABSTRACT: Print the resolved patah
# PODNAME:

=head1 SYNOPSIS

 % realpath [OPTION]... <FILE>...


=head1 DESCRIPTION

This is the Perl-based implementation alternative for the Unix utility
B<realpath>.

=head1 OPTIONS


=head1 EXIT CODES

0 on success.

99 on command-line options error.


=head1 FAQ


=head1 SEE ALSO

Unix utility B<realpath>

L<Cwd>

=cut
